import ExcelJS from 'exceljs';
import { PhaseRow, TierConfig, CostCategoryId } from '../types';
import { DEFAULT_TIERS } from '../data/defaultData';

export interface ImportedCampaignData {
  tracerName: string;
  selectedPresetId?: string;
  tiers: TierConfig[];
  rows: PhaseRow[];
  activeCostCategories?: CostCategoryId[];
  source: 'embedded_metadata' | 'csv_parsed' | 'html_parsed' | 'xlsx_parsed';
  timestamp?: string;
}

export interface ImportParseResult {
  success: boolean;
  data?: ImportedCampaignData;
  error?: string;
}

/**
 * Parses an exported report file (XLSX, CSV, HTML, DOC) generated by this webapp.
 */
export async function parseReportFile(fileInput: string | ArrayBuffer, fileName: string): Promise<ImportParseResult> {
  if (!fileInput) {
    return { success: false, error: 'The uploaded file appears to be empty.' };
  }

  // Handle ArrayBuffer input (e.g. from Excel file read as ArrayBuffer)
  if (fileInput instanceof ArrayBuffer) {
    try {
      const xlsxResult = await parseXlsxBuffer(fileInput);
      if (xlsxResult) {
        return { success: true, data: xlsxResult };
      }
    } catch (e) {
      console.warn('XLSX parsing failed on ArrayBuffer, falling back to text decoding:', e);
    }

    const textContent = new TextDecoder('utf-8').decode(fileInput);
    return parseTextContent(textContent, fileName);
  }

  // Handle string input
  if (typeof fileInput === 'string') {
    if (fileName.toLowerCase().endsWith('.xlsx') || fileName.toLowerCase().endsWith('.xls') || fileInput.startsWith('PK\x03\x04')) {
      try {
        const encoder = new TextEncoder();
        const buffer = encoder.encode(fileInput).buffer;
        const xlsxResult = await parseXlsxBuffer(buffer);
        if (xlsxResult) {
          return { success: true, data: xlsxResult };
        }
      } catch (e) {
        console.warn('XLSX parsing failed on string buffer, falling back to text parsers:', e);
      }
    }

    return parseTextContent(fileInput, fileName);
  }

  return { success: false, error: 'Unsupported file input type.' };
}

function parseTextContent(fileContent: string, fileName: string): ImportParseResult {
  if (!fileContent || !fileContent.trim()) {
    return { success: false, error: 'The uploaded file appears to be empty.' };
  }

  // 1. Check for Embedded JSON Metadata payload
  const metadataResult = extractEmbeddedMetadata(fileContent);
  if (metadataResult) {
    return { success: true, data: metadataResult };
  }

  // 2. Fallback: Parse as CSV if file is CSV or contains CSV headers
  if (fileName.toLowerCase().endsWith('.csv') || fileContent.includes('Tier Level,Phase Name') || fileContent.includes('Radiopharmaceuticals') || fileContent.includes('Isotope ($/b)')) {
    const csvResult = parseCsvFallback(fileContent);
    if (csvResult) {
      return { success: true, data: csvResult };
    }
  }

  // 3. Fallback: Parse as HTML / Word DOC
  if (fileContent.includes('<table') || fileContent.includes('<html') || fileContent.includes('<!DOCTYPE html>')) {
    const htmlResult = parseHtmlFallback(fileContent);
    if (htmlResult) {
      return { success: true, data: htmlResult };
    }
  }

  return {
    success: false,
    error: 'Could not recognize valid campaign budget report data in the selected file. Please make sure to import a report exported from this webapp (.xlsx, .csv, .doc, or .html).'
  };
}

/**
 * Parses native Excel (.xlsx) ArrayBuffer using ExcelJS
 */
async function parseXlsxBuffer(buffer: ArrayBuffer): Promise<ImportedCampaignData | null> {
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.load(buffer);

  // 1. Check for Embedded Metadata in any worksheet cell
  for (const sheet of workbook.worksheets) {
    for (let r = 1; r <= Math.min(sheet.rowCount, 250); r++) {
      const row = sheet.getRow(r);
      for (let c = 1; c <= Math.min(sheet.columnCount, 30); c++) {
        const cellVal = row.getCell(c).value;
        let strVal = '';
        if (typeof cellVal === 'string') {
          strVal = cellVal;
        } else if (typeof cellVal === 'object' && cellVal !== null && 'result' in cellVal) {
          strVal = String((cellVal as any).result || '');
        }

        if (strVal && strVal.includes('RADIOTRACER_APPLET_STATE')) {
          const match = strVal.match(/#\s*RADIOTRACER_APPLET_STATE:\s*(\{[\s\S]*?\})/);
          if (match && match[1]) {
            try {
              const parsed = JSON.parse(match[1]);
              if (parsed && Array.isArray(parsed.rows) && parsed.rows.length > 0) {
                return {
                  tracerName: parsed.tracerName || 'Imported Tracer',
                  selectedPresetId: parsed.selectedPresetId || 'custom',
                  tiers: Array.isArray(parsed.tiers) && parsed.tiers.length > 0 ? parsed.tiers : DEFAULT_TIERS,
                  rows: parsed.rows,
                  activeCostCategories: Array.isArray(parsed.activeCostCategories) ? parsed.activeCostCategories : undefined,
                  source: 'embedded_metadata',
                  timestamp: parsed.timestamp
                };
              }
            } catch (err) {
              console.warn('Failed to parse embedded metadata from XLSX cell:', err);
            }
          }
        }
      }
    }
  }

  // 2. Fallback: Parse worksheet cells directly
  const sheet = workbook.getWorksheet('Campaign Budget') || workbook.worksheets[0];
  if (!sheet) return null;

  let headerRowIdx = -1;
  sheet.eachRow((row, rowNumber) => {
    if (headerRowIdx !== -1) return;
    const r1 = String(row.getCell(1).value || '');
    const r2 = String(row.getCell(2).value || '');
    if ((r1.includes('Tier Level') || r1.includes('Tier')) && (r2.includes('Phase Name') || r2.includes('Phase'))) {
      headerRowIdx = rowNumber;
    }
  });

  if (headerRowIdx === -1) return null;

  const getCellNum = (cell: ExcelJS.Cell): number => {
    let val = cell.value;
    if (typeof val === 'object' && val !== null && 'result' in val) {
      val = (val as any).result;
    }
    if (typeof val === 'number') return val;
    if (typeof val === 'string') {
      const clean = val.replace(/[^0-9.-]/g, '');
      return parseFloat(clean) || 0;
    }
    return 0;
  };

  const getCellStr = (cell: ExcelJS.Cell): string => {
    let val = cell.value;
    if (typeof val === 'object' && val !== null && 'result' in val) {
      val = (val as any).result;
    }
    return val ? String(val).trim() : '';
  };

  // Build dynamic column index mapping from the header row
  const headerRow = sheet.getRow(headerRowIdx);
  const colMap = new Map<string, number>();
  for (let c = 1; c <= Math.max(headerRow.cellCount, 40); c++) {
    const headerText = getCellStr(headerRow.getCell(c)).toLowerCase();
    if (headerText) {
      colMap.set(headerText, c);
    }
  }

  const findCol = (predicate: (h: string) => boolean, fallbackIdx: number): number => {
    for (const [header, idx] of colMap.entries()) {
      if (predicate(header)) return idx;
    }
    return fallbackIdx;
  };

  const colTier = findCol(h => h.includes('tier'), 1);
  const colPhase = findCol(h => h.includes('phase name') || h.includes('phase'), 2);
  const colDesc = findCol(h => h.includes('desc'), 3);

  const colIsotope = findCol(h => h.includes('isotope'), 4);
  const colRadCon = findCol(h => h.includes('radio consumables') || (h.includes('consumables') && h.includes('$/b')), 5);
  const colRadRea = findCol(h => h.includes('radio reagents') || (h.includes('reagents') && h.includes('$/b')), 6);
  const colBatches = findCol(h => h.includes('batches') || h.includes('n_b'), 7);
  const colRadFac = findCol(h => h.includes('facility') && h.includes('$/h'), 8);
  const colRadTask = findCol(h => h.includes('task time') || h.includes('h/b'), 9);

  const colAnimals = findCol(h => h.includes('animals (n_a)') || h.includes('animals, n_a') || (h.includes('animal') && h.includes('n_a')), 11);
  const colAnimCost = findCol(h => h.includes('animal cost') || h.includes('animals ($/a)') || h.includes('animals, $/a'), 12);
  const colHousing = findCol(h => h.includes('housing'), 13);

  const colImgCon = findCol(h => (h.includes('preclin') || h.includes('imaging')) && (h.includes('consumables') || h.includes('$/s')), 15);
  const colImgRea = findCol(h => (h.includes('preclin') || h.includes('imaging')) && (h.includes('reagents') || h.includes('$/s')), 16);
  const colScans = findCol(h => (h.includes('preclin') && h.includes('scans')) || h.includes('scans (n_s)') || h.includes('scans, n_s') || h.includes('n_s'), 17);
  const colScanCost = findCol(h => (h.includes('preclin') || !h.includes('clin')) && h.includes('scan cost') && (h.includes('$/h') || h.includes('hour')), 18);
  const colScanTime = findCol(h => (h.includes('preclin') || !h.includes('clin')) && h.includes('scan time') && (h.includes('h/s') || h.includes('hour')), 19);
  const colImgAnalysisHours = findCol(h => (h.includes('preclin') || !h.includes('clin')) && h.includes('image analysis') && (h.includes('h/s') || h.includes('hour')), 20);
  const colImgAnalysisCost = findCol(h => (h.includes('preclin') || !h.includes('clin')) && h.includes('image analysis') && (h.includes('$/h') || h.includes('cost')), 21);

  const colClinImgCon = findCol(h => (h.includes('clin') || h.includes('clinical')) && h.includes('consumables') && (h.includes('$/cs') || h.includes('scan')), 22);
  const colClinImgRea = findCol(h => (h.includes('clin') || h.includes('clinical')) && h.includes('reagents') && (h.includes('$/cs') || h.includes('scan')), 23);
  const colClinScans = findCol(h => (h.includes('clin') || h.includes('clinical')) && (h.includes('scans') || h.includes('n_cs')), 24);
  const colClinScanCost = findCol(h => (h.includes('clin') || h.includes('clinical')) && h.includes('scan cost') && (h.includes('$/h') || h.includes('hour')), 25);
  const colClinScanTime = findCol(h => (h.includes('clin') || h.includes('clinical')) && h.includes('scan time') && (h.includes('h/cs') || h.includes('hour')), 26);
  const colClinImgAnalysisHours = findCol(h => (h.includes('clin') || h.includes('clinical')) && h.includes('image analysis') && (h.includes('h/cs') || h.includes('hour')), 27);
  const colClinImgAnalysisCost = findCol(h => (h.includes('clin') || h.includes('clinical')) && h.includes('image analysis') && (h.includes('$/h') || h.includes('cost')), 28);

  const colBioCon = findCol(h => (h.includes('bio consumables') || h.includes('consumables')) && (h.includes('$/bio') || h.includes('biodistribution')), 30);
  const colBioRea = findCol(h => (h.includes('bio reagents') || h.includes('reagents')) && (h.includes('$/bio') || h.includes('biodistribution')), 31);
  const colBios = findCol(h => h.includes('biodistributions') || h.includes('n_bio'), 32);
  const colBioCost = findCol(h => h.includes('bio cost') || h.includes('$/unit') || h.includes('$/n_bio'), 33);

  const colCellLine = findCol(h => h.includes('cell line'), 35);
  const colInVitroCon = findCol(h => (h.includes('in vitro consumables') || h.includes('consumables')) && h.includes('$/t'), 36);
  const colInVitroRea = findCol(h => (h.includes('in vitro reagents') || h.includes('reagents')) && h.includes('$/t'), 37);
  const colInVitroTests = findCol(h => h.includes('in vitro tests') || h.includes('tests (n_t)') || h.includes('n_t'), 38);
  const colInVitroTestingHours = findCol(h => h.includes('in vitro testing') && (h.includes('h/t') || h.includes('testing, h/t')), 39);
  const colInVitroTestingCost = findCol(h => (h.includes('testing cost') || h.includes('testing')) && h.includes('$/h'), 40);

  const colOthers = findCol(h => h.includes('others cost') || h.includes('other direct') || h.includes('others, $'), 42);
  const colOthersNotes = findCol(h => h.includes('note (others)') || h.includes('other note'), 43);
  const colPhaseNotes = findCol(h => h.includes('phase notes') || h.includes('phase note') || h.includes('notes'), 44);

  const parsedRows: PhaseRow[] = [];
  const foundTiers = new Set<number>();

  for (let r = headerRowIdx + 1; r <= sheet.rowCount; r++) {
    const row = sheet.getRow(r);
    const tierCellStr = getCellStr(row.getCell(colTier));
    if (tierCellStr.includes('TOTAL') || tierCellStr.includes('CORE SECTION') || tierCellStr.startsWith('#')) {
      break;
    }

    const tierNum = parseInt(tierCellStr.replace(/[^0-9]/g, ''), 10) || 1;
    const phaseName = getCellStr(row.getCell(colPhase));
    if (!phaseName) continue;

    foundTiers.add(tierNum);

    const rowObj: PhaseRow = {
      id: `xlsx-imported-row-${Date.now()}-${r}`,
      tier: tierNum,
      phase: phaseName,
      description: getCellStr(row.getCell(colDesc)),

      isotopeCostPerBatch: getCellNum(row.getCell(colIsotope)),
      radiopharmConsumablesPerBatch: getCellNum(row.getCell(colRadCon)),
      radiopharmReagentsPerBatch: getCellNum(row.getCell(colRadRea)),
      numBatches: getCellNum(row.getCell(colBatches)),
      radiopharmFacilityCostPerHour: getCellNum(row.getCell(colRadFac)),
      radiopharmTaskTimeHoursPerBatch: getCellNum(row.getCell(colRadTask)),

      numAnimals: getCellNum(row.getCell(colAnimals)),
      animalCostEach: getCellNum(row.getCell(colAnimCost)),
      housingCostEach: getCellNum(row.getCell(colHousing)),

      imagingConsumablesPerScan: getCellNum(row.getCell(colImgCon)),
      imagingReagentsPerScan: getCellNum(row.getCell(colImgRea)),
      numScans: getCellNum(row.getCell(colScans)),
      scanCostPerHour: getCellNum(row.getCell(colScanCost)),
      scanTimeHoursPerScan: getCellNum(row.getCell(colScanTime)),
      imageAnalysisHoursPerScan: getCellNum(row.getCell(colImgAnalysisHours)),
      imageAnalysisCostPerHour: getCellNum(row.getCell(colImgAnalysisCost)),

      clinicalImagingConsumablesPerScan: getCellNum(row.getCell(colClinImgCon)),
      clinicalImagingReagentsPerScan: getCellNum(row.getCell(colClinImgRea)),
      numClinicalScans: getCellNum(row.getCell(colClinScans)),
      clinicalScanCostPerHour: getCellNum(row.getCell(colClinScanCost)),
      clinicalScanTimeHoursPerScan: getCellNum(row.getCell(colClinScanTime)),
      clinicalImageAnalysisHoursPerScan: getCellNum(row.getCell(colClinImgAnalysisHours)),
      clinicalImageAnalysisCostPerHour: getCellNum(row.getCell(colClinImgAnalysisCost)),

      bioConsumablesPerBio: getCellNum(row.getCell(colBioCon)),
      bioReagentsPerBio: getCellNum(row.getCell(colBioRea)),
      numBiodistributions: getCellNum(row.getCell(colBios)),
      bioCostPerUnit: getCellNum(row.getCell(colBioCost)),

      cellLineCost: getCellNum(row.getCell(colCellLine)),
      inVitroConsumablesPerTest: getCellNum(row.getCell(colInVitroCon)),
      inVitroReagentsPerTest: getCellNum(row.getCell(colInVitroRea)),
      numInVitroTests: getCellNum(row.getCell(colInVitroTests)),
      inVitroTestingHoursPerTest: getCellNum(row.getCell(colInVitroTestingHours)),
      inVitroTestingCostPerHour: getCellNum(row.getCell(colInVitroTestingCost)),

      othersCost: getCellNum(row.getCell(colOthers)),
      othersNotes: getCellStr(row.getCell(colOthersNotes)),
      phaseNotes: getCellStr(row.getCell(colPhaseNotes)),
      notes: getCellStr(row.getCell(colPhaseNotes))
    };

    parsedRows.push(rowObj);
  }

  if (parsedRows.length === 0) return null;

  // Check Itemization Breakdown worksheet
  const itemSheet = workbook.getWorksheet('Itemization Breakdown');
  if (itemSheet) {
    parseXlsxItemizations(itemSheet, parsedRows);
  }

  let tracerName = 'Imported Campaign';
  const a1 = getCellStr(sheet.getCell('A1'));
  if (a1 && a1.includes('-')) {
    const parts = a1.split('-');
    tracerName = parts[parts.length - 1].trim();
  }

  const tierList: TierConfig[] = Array.from(foundTiers).sort((a, b) => a - b).map(num => {
    const existingDefault = DEFAULT_TIERS.find(t => t.tierNumber === num);
    return existingDefault || {
      tierNumber: num,
      name: `Tier ${num} Package`,
      subtitle: `Imported Campaign Scope Tier ${num}`
    };
  });

  return {
    tracerName: tracerName || 'Imported Campaign',
    selectedPresetId: 'custom',
    tiers: tierList.length > 0 ? tierList : DEFAULT_TIERS,
    rows: parsedRows,
    source: 'xlsx_parsed'
  };
}

function parseXlsxItemizations(itemSheet: ExcelJS.Worksheet, rows: PhaseRow[]) {
  itemSheet.eachRow((row, rowNumber) => {
    if (rowNumber < 4) return;
    const tierText = String(row.getCell(1).value || '');
    const tierNum = parseInt(tierText.replace(/[^0-9]/g, ''), 10) || 1;
    const phaseName = String(row.getCell(2).value || '').trim();
    const fieldLabel = String(row.getCell(4).value || '').trim();
    const breakdownStr = String(row.getCell(5).value || '').trim();

    if (!phaseName || !fieldLabel || !breakdownStr) return;

    const targetRow = rows.find(r => r.tier === tierNum && r.phase.toLowerCase() === phaseName.toLowerCase());
    if (!targetRow) return;

    if (!targetRow.itemizations) {
      targetRow.itemizations = {};
    }

    const keyMap: Record<string, keyof PhaseRow> = {
      'Isotope Cost ($/b)': 'isotopeCostPerBatch',
      'Radiopharm Consumables ($/b)': 'radiopharmConsumablesPerBatch',
      'Radiopharm Reagents ($/b)': 'radiopharmReagentsPerBatch',
      'Production Batches (n_b)': 'numBatches',
      'Facility Rate ($/h)': 'radiopharmFacilityCostPerHour',
      'Task Duration (h/b)': 'radiopharmTaskTimeHoursPerBatch',

      'Animal Quantity (n_a)': 'numAnimals',
      'Animal Purchase Cost ($/a)': 'animalCostEach',
      'Housing Cost ($/a)': 'housingCostEach',

      'Imaging Consumables ($/s)': 'imagingConsumablesPerScan',
      'Imaging Reagents ($/s)': 'imagingReagentsPerScan',
      'Scan Quantity (n_s)': 'numScans',
      'Scan Rate ($/h)': 'scanCostPerHour',
      'Scan Duration (h/s)': 'scanTimeHoursPerScan',
      'Image Analysis Duration (h/s)': 'imageAnalysisHoursPerScan',
      'Image Analysis Rate ($/h)': 'imageAnalysisCostPerHour',

      'Biodistribution Consumables ($/bio)': 'bioConsumablesPerBio',
      'Biodistribution Reagents ($/bio)': 'bioReagentsPerBio',
      'Biodistribution Quantity (n_bio)': 'numBiodistributions',
      'Biodistribution Unit Cost ($/unit)': 'bioCostPerUnit',

      'Cell Line Cost ($)': 'cellLineCost',
      'In Vitro Consumables ($/t)': 'inVitroConsumablesPerTest',
      'In Vitro Reagents ($/t)': 'inVitroReagentsPerTest',
      'In Vitro Test Quantity (n_t)': 'numInVitroTests',
      'In Vitro Testing Duration (h/t)': 'inVitroTestingHoursPerTest',
      'In Vitro Testing Rate ($/h)': 'inVitroTestingCostPerHour',

      'Other Direct Costs ($)': 'othersCost',

      // shorthand / legacy labels
      'Isotope, $/b': 'isotopeCostPerBatch',
      'Consumables, $/b': 'radiopharmConsumablesPerBatch',
      'Reagents, $/b': 'radiopharmReagentsPerBatch',
      'Facility, $/h': 'radiopharmFacilityCostPerHour',
      'Task time, h/b': 'radiopharmTaskTimeHoursPerBatch',
      'Animals, $/a': 'animalCostEach',
      'Housing, $/a': 'housingCostEach',
      'Consumables, $/s': 'imagingConsumablesPerScan',
      'Reagents, $/s': 'imagingReagentsPerScan',
      'Scan cost, $/h': 'scanCostPerHour',
      'Scan time, h/s': 'scanTimeHoursPerScan',
      'Image analysis, h/s': 'imageAnalysisHoursPerScan',
      'Image analysis, $/h': 'imageAnalysisCostPerHour',
      'Consumables, $/bio': 'bioConsumablesPerBio',
      'Reagents, $/bio': 'bioReagentsPerBio',
      'Biodistribution cost, $/n_bio': 'bioCostPerUnit',
      'Cell line, $': 'cellLineCost',
      'Consumables, $/t': 'inVitroConsumablesPerTest',
      'Reagents, $/t': 'inVitroReagentsPerTest',
      'Tests, n_t': 'numInVitroTests',
      'Testing, h/t': 'inVitroTestingHoursPerTest',
      'Testing cost, $/h': 'inVitroTestingCostPerHour',
      'Others Cost, $': 'othersCost'
    };

    const fieldKey = keyMap[fieldLabel] || fieldLabel;
    if (!targetRow.itemizations[fieldKey as string]) {
      targetRow.itemizations[fieldKey as string] = [];
    }

    const itemTokens = breakdownStr.includes(';') ? breakdownStr.split(';') : [breakdownStr];
    itemTokens.forEach(token => {
      const parts = token.split(':');
      let name = token.trim();
      let val = 0;
      if (parts.length >= 2) {
        name = parts[0].trim();
        const rawVal = parts.slice(1).join(':').replace(/[^0-9.-]/g, '');
        val = parseFloat(rawVal) || 0;
      }
      if (name) {
        targetRow.itemizations[fieldKey as string].push({
          id: `imported-xlsx-item-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
          name,
          value: val
        });
      }
    });
  });
}

/**
 * Attempts to locate embedded JSON metadata in CSV comment, HTML script, or HTML comment
 */
function extractEmbeddedMetadata(content: string): ImportedCampaignData | null {
  try {
    let jsonStr: string | null = null;

    // Pattern A: Script tag <script id="radiotracer-applet-state" type="application/json">...</script>
    const scriptMatch = content.match(/<script[^>]*id=["']radiotracer-applet-state["'][^>]*>([\s\S]*?)<\/script>/i);
    if (scriptMatch && scriptMatch[1]) {
      jsonStr = scriptMatch[1].trim();
    }

    // Pattern B: HTML comment <!-- RADIOTRACER_APPLET_STATE: {...} -->
    if (!jsonStr) {
      const commentMatch = content.match(/<!--\s*RADIOTRACER_APPLET_STATE:\s*(\{[\s\S]*?\})\s*-->/);
      if (commentMatch && commentMatch[1]) {
        jsonStr = commentMatch[1].trim();
      }
    }

    // Pattern C: CSV metadata line `# RADIOTRACER_APPLET_STATE: {...}`
    if (!jsonStr) {
      const csvMatch = content.match(/#\s*RADIOTRACER_APPLET_STATE:\s*(\{[\s\S]*?\})(?:\r?\n|$)/);
      if (csvMatch && csvMatch[1]) {
        jsonStr = csvMatch[1].trim();
      }
    }

    if (!jsonStr) return null;

    const parsed = JSON.parse(jsonStr);

    if (parsed && Array.isArray(parsed.rows) && parsed.rows.length > 0) {
      return {
        tracerName: parsed.tracerName || 'Imported Tracer',
        selectedPresetId: parsed.selectedPresetId || 'custom',
        tiers: Array.isArray(parsed.tiers) && parsed.tiers.length > 0 ? parsed.tiers : DEFAULT_TIERS,
        rows: parsed.rows,
        activeCostCategories: Array.isArray(parsed.activeCostCategories) ? parsed.activeCostCategories : undefined,
        source: 'embedded_metadata',
        timestamp: parsed.timestamp
      };
    }
  } catch (err) {
    console.warn('Failed to parse embedded metadata JSON, falling back to document parsing:', err);
  }

  return null;
}

/**
 * Fallback parser for CSV exports without metadata
 */
function parseCsvFallback(content: string): ImportedCampaignData | null {
  try {
    const rawLines = content.split(/\r?\n/);
    const lines = rawLines.map(l => l.trim()).filter(l => l.length > 0);

    // Find main table header line
    let headerIdx = lines.findIndex(l => l.includes('Tier Level') && l.includes('Phase Name'));
    if (headerIdx === -1) {
      headerIdx = lines.findIndex(l => l.includes('Phase Name'));
    }

    if (headerIdx === -1) return null;

    const headers = parseCsvLine(lines[headerIdx]);
    const getCol = (name: string) => headers.findIndex(h => h.toLowerCase().includes(name.toLowerCase()));

    const colTier = getCol('Tier Level') !== -1 ? getCol('Tier Level') : 0;
    const colPhase = getCol('Phase Name') !== -1 ? getCol('Phase Name') : 1;
    const colDesc = getCol('Description') !== -1 ? getCol('Description') : 2;

    const colIsotope = getCol('Isotope');
    const colRadCon = getCol('Radio Consumables');
    const colRadRea = getCol('Radio Reagents');
    const colBatches = getCol('Batches');
    const colRadFac = getCol('Facility');
    const colRadTask = getCol('Task Time');

    const colAnimals = getCol('Animals (n_a)');
    const colAnimCost = getCol('Animal Cost');
    const colHousing = getCol('Housing');

    const colImgCon = getCol('Imaging Consumables') !== -1 ? getCol('Imaging Consumables') : getCol('Preclin Consumables');
    const colImgRea = getCol('Imaging Reagents') !== -1 ? getCol('Imaging Reagents') : getCol('Preclin Reagents');
    const colScans = getCol('Scans (n_s)') !== -1 ? getCol('Scans (n_s)') : (getCol('Preclin Scans') !== -1 ? getCol('Preclin Scans') : getCol('Scans'));
    const colScanCost = getCol('Scan Cost ($/h)') !== -1 ? getCol('Scan Cost ($/h)') : getCol('Scan Cost');
    const colScanTime = getCol('Scan Time (h/s)') !== -1 ? getCol('Scan Time (h/s)') : getCol('Scan Time');
    const colImgAnalysisHours = getCol('Image Analysis (h/s)') !== -1 ? getCol('Image Analysis (h/s)') : getCol('Image analysis, h/s');
    const colImgAnalysisCost = getCol('Image Analysis ($/h)') !== -1 ? getCol('Image Analysis ($/h)') : getCol('Image analysis, $/h');

    const colClinImgCon = getCol('Clin Consumables') !== -1 ? getCol('Clin Consumables') : getCol('Clinical Consumables');
    const colClinImgRea = getCol('Clin Reagents') !== -1 ? getCol('Clin Reagents') : getCol('Clinical Reagents');
    const colClinScans = getCol('Clin Scans (n_cs)') !== -1 ? getCol('Clin Scans (n_cs)') : (getCol('Clinical Scans') !== -1 ? getCol('Clinical Scans') : getCol('Clin Scans'));
    const colClinScanCost = getCol('Clin Scan Cost ($/h)') !== -1 ? getCol('Clin Scan Cost ($/h)') : getCol('Clinical Scan Cost');
    const colClinScanTime = getCol('Clin Scan Time (h/cs)') !== -1 ? getCol('Clin Scan Time (h/cs)') : getCol('Clinical Scan Time');
    const colClinImgAnalysisHours = getCol('Clin Analysis (h/cs)') !== -1 ? getCol('Clin Analysis (h/cs)') : getCol('Clinical Analysis Time');
    const colClinImgAnalysisCost = getCol('Clin Analysis ($/h)') !== -1 ? getCol('Clin Analysis ($/h)') : getCol('Clinical Analysis Cost');

    const colBioCon = getCol('Bio Consumables');
    const colBioRea = getCol('Bio Reagents');
    const colBios = getCol('Biodistributions');
    const colBioCost = getCol('Bio Cost');

    const colCellLine = getCol('Cell Line') !== -1 ? getCol('Cell Line') : getCol('Cell line');
    const colInVitroCon = getCol('In Vitro Consumables') !== -1 ? getCol('In Vitro Consumables') : getCol('Consumables ($/t)');
    const colInVitroRea = getCol('In Vitro Reagents') !== -1 ? getCol('In Vitro Reagents') : getCol('Reagents ($/t)');
    const colInVitroTests = getCol('In Vitro Tests') !== -1 ? getCol('In Vitro Tests') : getCol('Tests (n_t)');
    const colInVitroTestingHours = getCol('In Vitro Testing (h/t)') !== -1 ? getCol('In Vitro Testing (h/t)') : getCol('Testing (h/t)');
    const colInVitroTestingCost = getCol('Testing Cost ($/h)') !== -1 ? getCol('Testing Cost ($/h)') : getCol('Testing cost, $/h');

    const colOthers = getCol('Others Cost');
    const colOthersNotes = getCol('Note (Others)');
    const colPhaseNotes = getCol('Phase Notes');

    const parsedRows: PhaseRow[] = [];
    const foundTiers = new Set<number>();

    // Parse Phase Rows until section separator
    for (let i = headerIdx + 1; i < lines.length; i++) {
      const line = lines[i];
      if (line.startsWith('"===') || line.startsWith('#') || line.startsWith('===') || line.includes('CORE SECTION COST')) {
        break; // Reached analytics/itemization sections
      }

      const cols = parseCsvLine(line);
      if (cols.length < 3) continue;

      const tierNum = parseInt(cols[colTier], 10) || 1;
      const phaseName = cols[colPhase] ? cols[colPhase].replace(/^"|"$/g, '').trim() : '';

      if (!phaseName) continue;

      foundTiers.add(tierNum);

      const parseNum = (valIdx: number) => {
        if (valIdx === -1 || !cols[valIdx]) return 0;
        const clean = cols[valIdx].replace(/[^0-9.-]/g, '');
        return parseFloat(clean) || 0;
      };

      const parseStr = (valIdx: number) => {
        if (valIdx === -1 || !cols[valIdx]) return '';
        return cols[valIdx].replace(/^"|"$/g, '').trim();
      };

      const rowObj: PhaseRow = {
        id: `imported-row-${Date.now()}-${i}`,
        tier: tierNum,
        phase: phaseName,
        description: parseStr(colDesc),

        isotopeCostPerBatch: parseNum(colIsotope),
        radiopharmConsumablesPerBatch: parseNum(colRadCon),
        radiopharmReagentsPerBatch: parseNum(colRadRea),
        numBatches: parseNum(colBatches),
        radiopharmFacilityCostPerHour: parseNum(colRadFac),
        radiopharmTaskTimeHoursPerBatch: parseNum(colRadTask),

        numAnimals: parseNum(colAnimals),
        animalCostEach: parseNum(colAnimCost),
        housingCostEach: parseNum(colHousing),

        imagingConsumablesPerScan: parseNum(colImgCon),
        imagingReagentsPerScan: parseNum(colImgRea),
        numScans: parseNum(colScans),
        scanCostPerHour: parseNum(colScanCost),
        scanTimeHoursPerScan: parseNum(colScanTime),
        imageAnalysisHoursPerScan: parseNum(colImgAnalysisHours),
        imageAnalysisCostPerHour: parseNum(colImgAnalysisCost),

        clinicalImagingConsumablesPerScan: parseNum(colClinImgCon),
        clinicalImagingReagentsPerScan: parseNum(colClinImgRea),
        numClinicalScans: parseNum(colClinScans),
        clinicalScanCostPerHour: parseNum(colClinScanCost),
        clinicalScanTimeHoursPerScan: parseNum(colClinScanTime),
        clinicalImageAnalysisHoursPerScan: parseNum(colClinImgAnalysisHours),
        clinicalImageAnalysisCostPerHour: parseNum(colClinImgAnalysisCost),

        bioConsumablesPerBio: parseNum(colBioCon),
        bioReagentsPerBio: parseNum(colBioRea),
        numBiodistributions: parseNum(colBios),
        bioCostPerUnit: parseNum(colBioCost),

        cellLineCost: parseNum(colCellLine),
        inVitroConsumablesPerTest: parseNum(colInVitroCon),
        inVitroReagentsPerTest: parseNum(colInVitroRea),
        numInVitroTests: parseNum(colInVitroTests),
        inVitroTestingHoursPerTest: parseNum(colInVitroTestingHours),
        inVitroTestingCostPerHour: parseNum(colInVitroTestingCost),

        othersCost: parseNum(colOthers),
        othersNotes: parseStr(colOthersNotes),
        phaseNotes: parseStr(colPhaseNotes) || parseStr(colOthersNotes),
        notes: parseStr(colPhaseNotes)
      };

      parsedRows.push(rowObj);
    }

    if (parsedRows.length === 0) return null;

    // Reconstruct itemizations if itemization section is present in CSV
    const itemSectionIdx = lines.findIndex(l => l.includes('ITEMIZATION LINE ITEM BREAKDOWN'));
    if (itemSectionIdx !== -1) {
      parseCsvItemizations(lines.slice(itemSectionIdx + 1), parsedRows);
    }

    // Build TierConfigs from found tiers
    const tierList: TierConfig[] = Array.from(foundTiers).sort((a, b) => a - b).map(num => {
      const existingDefault = DEFAULT_TIERS.find(t => t.tierNumber === num);
      return existingDefault || {
        tierNumber: num,
        name: `Tier ${num} Package`,
        subtitle: `Imported Campaign Scope Tier ${num}`
      };
    });

    // Try extracting Tracer Name from CSV header if present
    let tracerName = 'Imported Campaign';
    const firstLine = lines[0];
    if (firstLine.includes('Report') || firstLine.includes('Tracer')) {
      tracerName = firstLine.replace(/[^a-zA-Z0-9\s[\]\-_]/g, '').trim() || 'Imported Campaign';
    }

    return {
      tracerName,
      selectedPresetId: 'custom',
      tiers: tierList.length > 0 ? tierList : DEFAULT_TIERS,
      rows: parsedRows,
      source: 'csv_parsed'
    };
  } catch (err) {
    console.warn('Error during CSV fallback parsing:', err);
    return null;
  }
}

/**
 * Parses itemizations block in CSV and attaches items back to corresponding PhaseRow fields
 */
function parseCsvItemizations(lines: string[], rows: PhaseRow[]) {
  lines.forEach(line => {
    const cols = parseCsvLine(line);
    if (cols.length < 5) return;
    const tierNum = parseInt(cols[0], 10);
    const phaseName = cols[1].replace(/^"|"$/g, '').trim();
    const fieldLabel = cols[3].replace(/^"|"$/g, '').trim();
    const breakdownStr = cols[4].replace(/^"|"$/g, '').trim();

    if (!phaseName || !fieldLabel || !breakdownStr) return;

    // Find row
    const targetRow = rows.find(r => r.tier === tierNum && r.phase.toLowerCase() === phaseName.toLowerCase());
    if (!targetRow) return;

    if (!targetRow.itemizations) {
      targetRow.itemizations = {};
    }

    // Map field label back to property key
    const keyMap: Record<string, keyof PhaseRow> = {
      'Isotope Cost ($/b)': 'isotopeCostPerBatch',
      'Radiopharm Consumables ($/b)': 'radiopharmConsumablesPerBatch',
      'Radiopharm Reagents ($/b)': 'radiopharmReagentsPerBatch',
      'Production Batches (n_b)': 'numBatches',
      'Facility Rate ($/h)': 'radiopharmFacilityCostPerHour',
      'Task Duration (h/b)': 'radiopharmTaskTimeHoursPerBatch',

      'Animal Quantity (n_a)': 'numAnimals',
      'Animal Purchase Cost ($/a)': 'animalCostEach',
      'Housing Cost ($/a)': 'housingCostEach',

      'Imaging Consumables ($/s)': 'imagingConsumablesPerScan',
      'Imaging Reagents ($/s)': 'imagingReagentsPerScan',
      'Scan Quantity (n_s)': 'numScans',
      'Scan Rate ($/h)': 'scanCostPerHour',
      'Scan Duration (h/s)': 'scanTimeHoursPerScan',
      'Image Analysis Duration (h/s)': 'imageAnalysisHoursPerScan',
      'Image Analysis Rate ($/h)': 'imageAnalysisCostPerHour',

      'Biodistribution Consumables ($/bio)': 'bioConsumablesPerBio',
      'Biodistribution Reagents ($/bio)': 'bioReagentsPerBio',
      'Biodistribution Quantity (n_bio)': 'numBiodistributions',
      'Biodistribution Unit Cost ($/unit)': 'bioCostPerUnit',

      'Cell Line Cost ($)': 'cellLineCost',
      'In Vitro Consumables ($/t)': 'inVitroConsumablesPerTest',
      'In Vitro Reagents ($/t)': 'inVitroReagentsPerTest',
      'In Vitro Test Quantity (n_t)': 'numInVitroTests',
      'In Vitro Testing Duration (h/t)': 'inVitroTestingHoursPerTest',
      'In Vitro Testing Rate ($/h)': 'inVitroTestingCostPerHour',

      'Other Direct Costs ($)': 'othersCost',

      // legacy and shorthand labels support
      'Isotope, $/b': 'isotopeCostPerBatch',
      'Consumables, $/b': 'radiopharmConsumablesPerBatch',
      'Reagents, $/b': 'radiopharmReagentsPerBatch',
      'Facility, $/h': 'radiopharmFacilityCostPerHour',
      'Task time, h/b': 'radiopharmTaskTimeHoursPerBatch',
      'Animals, $/a': 'animalCostEach',
      'Housing, $/a': 'housingCostEach',
      'Consumables, $/s': 'imagingConsumablesPerScan',
      'Reagents, $/s': 'imagingReagentsPerScan',
      'Scan cost, $/h': 'scanCostPerHour',
      'Scan time, h/s': 'scanTimeHoursPerScan',
      'Image analysis, h/s': 'imageAnalysisHoursPerScan',
      'Image analysis, $/h': 'imageAnalysisCostPerHour',
      'Consumables, $/bio': 'bioConsumablesPerBio',
      'Reagents, $/bio': 'bioReagentsPerBio',
      'Biodistribution cost, $/n_bio': 'bioCostPerUnit',
      'Cell line, $': 'cellLineCost',
      'Consumables, $/t': 'inVitroConsumablesPerTest',
      'Reagents, $/t': 'inVitroReagentsPerTest',
      'Tests, n_t': 'numInVitroTests',
      'Testing, h/t': 'inVitroTestingHoursPerTest',
      'Testing cost, $/h': 'inVitroTestingCostPerHour',
      'Others Cost, $': 'othersCost'
    };

    const fieldKey = keyMap[fieldLabel] || fieldLabel;
    if (!targetRow.itemizations[fieldKey as string]) {
      targetRow.itemizations[fieldKey as string] = [];
    }

    // Split by semicolon (;) if grouped row
    const itemTokens = breakdownStr.includes(';') ? breakdownStr.split(';') : [breakdownStr];
    itemTokens.forEach(token => {
      const parts = token.split(':');
      let name = token.trim();
      let val = 0;
      if (parts.length >= 2) {
        name = parts[0].trim();
        const rawVal = parts.slice(1).join(':').replace(/[^0-9.-]/g, '');
        val = parseFloat(rawVal) || 0;
      } else if (cols[5]) {
        val = parseFloat(cols[5].replace(/[^0-9.-]/g, '')) || 0;
      }
      if (name) {
        targetRow.itemizations[fieldKey as string].push({
          id: `imported-item-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
          name,
          value: val
        });
      }
    });
  });
}

/**
 * Fallback parser for HTML / Word export files
 */
function parseHtmlFallback(htmlContent: string): ImportedCampaignData | null {
  try {
    const parser = new DOMParser();
    const doc = parser.parseFromString(htmlContent, 'text/html');

    // Extract tracer name from h1
    const h1 = doc.querySelector('h1');
    let tracerName = 'Imported Campaign';
    if (h1 && h1.textContent) {
      tracerName = h1.textContent.replace('Radiotracer Campaign Budget Report', '').replace('Budget Report', '').trim();
    }

    const tableRows = doc.querySelectorAll('table tbody tr');
    if (!tableRows || tableRows.length === 0) return null;

    const parsedRows: PhaseRow[] = [];
    const foundTiers = new Set<number>();

    // Check if full parametric table is present (rows with >= 35 columns)
    const fullRows = Array.from(tableRows).filter(tr => tr.querySelectorAll('td').length >= 35);

    if (fullRows.length > 0) {
      // Parse from full parametric table
      fullRows.forEach((tr, idx) => {
        const tds = tr.querySelectorAll('td');
        const tierText = tds[0].textContent || '';
        const tierMatch = tierText.match(/\d+/);
        const tierNum = tierMatch ? parseInt(tierMatch[0], 10) : 1;

        const phaseName = (tds[1].textContent || '').trim();
        const description = (tds[2].textContent || '').trim();

        if (!phaseName || phaseName.toLowerCase().includes('total')) return;

        foundTiers.add(tierNum);

        const parseNum = (cell: Element | undefined) => parseFloat(cell?.textContent?.replace(/[^0-9.-]/g, '') || '0') || 0;

        const rowObj: PhaseRow = {
          id: `html-full-row-${Date.now()}-${idx}`,
          tier: tierNum,
          phase: phaseName,
          description,

          // Radio
          isotopeCostPerBatch: parseNum(tds[3]),
          radiopharmConsumablesPerBatch: parseNum(tds[4]),
          radiopharmReagentsPerBatch: parseNum(tds[5]),
          numBatches: parseNum(tds[6]),
          radiopharmFacilityCostPerHour: parseNum(tds[7]),
          radiopharmTaskTimeHoursPerBatch: parseNum(tds[8]),

          // Animals
          numAnimals: parseNum(tds[10]),
          animalCostEach: parseNum(tds[11]),
          housingCostEach: parseNum(tds[12]),

          // Preclinical Imaging
          imagingConsumablesPerScan: parseNum(tds[14]),
          imagingReagentsPerScan: parseNum(tds[15]),
          numScans: parseNum(tds[16]),
          scanCostPerHour: parseNum(tds[17]),
          scanTimeHoursPerScan: parseNum(tds[18]),
          imageAnalysisHoursPerScan: parseNum(tds[19]),
          imageAnalysisCostPerHour: parseNum(tds[20]),

          // Clinical Imaging
          clinicalImagingConsumablesPerScan: parseNum(tds[21]),
          clinicalImagingReagentsPerScan: parseNum(tds[22]),
          numClinicalScans: parseNum(tds[23]),
          clinicalScanCostPerHour: parseNum(tds[24]),
          clinicalScanTimeHoursPerScan: parseNum(tds[25]),
          clinicalImageAnalysisHoursPerScan: parseNum(tds[26]),
          clinicalImageAnalysisCostPerHour: parseNum(tds[27]),

          // Biodistribution
          bioConsumablesPerBio: parseNum(tds[29] || tds[22]),
          bioReagentsPerBio: parseNum(tds[30] || tds[23]),
          numBiodistributions: parseNum(tds[31] || tds[24]),
          bioCostPerUnit: parseNum(tds[32] || tds[25]),

          // In Vitro
          cellLineCost: parseNum(tds[34] || tds[27]),
          inVitroConsumablesPerTest: parseNum(tds[35] || tds[28]),
          inVitroReagentsPerTest: parseNum(tds[36] || tds[29]),
          numInVitroTests: parseNum(tds[37] || tds[30]),
          inVitroTestingHoursPerTest: parseNum(tds[38] || tds[31]),
          inVitroTestingCostPerHour: parseNum(tds[39] || tds[32]),

          // Others & Notes
          othersCost: parseNum(tds[41] || tds[34]),
          othersNotes: (tds[42] || tds[35])?.textContent?.trim() || '',
          phaseNotes: (tds[43] || tds[36])?.textContent?.trim() || '',
          notes: (tds[43] || tds[36])?.textContent?.trim() || ''
        };

        parsedRows.push(rowObj);
      });
    } else {
      // Parse from summarized matrix table
      tableRows.forEach((tr, idx) => {
        const tds = tr.querySelectorAll('td');
        if (tds.length < 9 || tds.length >= 35) return; // Not summarized matrix table

        const tierText = tds[0].textContent || '';
        const tierMatch = tierText.match(/\d+/);
        const tierNum = tierMatch ? parseInt(tierMatch[0], 10) : 1;

        const phaseTd = tds[1];
        const phaseName = phaseTd ? (phaseTd.querySelector('strong')?.textContent || phaseTd.childNodes[0]?.textContent || '').trim() : '';
        const description = phaseTd ? (phaseTd.querySelector('small')?.textContent || '').trim() : '';

        if (!phaseName || phaseName.toLowerCase().includes('total')) return;

        foundTiers.add(tierNum);

        const numBatches = parseFloat(tds[2]?.textContent?.replace(/[^0-9.-]/g, '') || '0') || 0;
        const radioTotal = parseFloat(tds[3]?.textContent?.replace(/[^0-9.-]/g, '') || '0') || 0;

        const numAnimals = parseFloat(tds[4]?.textContent?.replace(/[^0-9.-]/g, '') || '0') || 0;
        const animalTotal = parseFloat(tds[5]?.textContent?.replace(/[^0-9.-]/g, '') || '0') || 0;

        const numScans = parseFloat(tds[6]?.textContent?.replace(/[^0-9.-]/g, '') || '0') || 0;
        const imagingTotal = parseFloat(tds[7]?.textContent?.replace(/[^0-9.-]/g, '') || '0') || 0;

        const is7Category = tds.length >= 15;
        const is6Category = tds.length >= 13 && !is7Category;

        const numClinicalScans = is7Category ? parseFloat(tds[8]?.textContent?.replace(/[^0-9.-]/g, '') || '0') || 0 : 0;
        const clinicalImagingTotal = is7Category ? parseFloat(tds[9]?.textContent?.replace(/[^0-9.-]/g, '') || '0') || 0 : 0;

        const bioColIdx = is7Category ? 10 : 8;
        const numBiodistributions = parseFloat(tds[bioColIdx]?.textContent?.replace(/[^0-9.-]/g, '') || '0') || 0;
        const biodistributionTotal = parseFloat(tds[bioColIdx + 1]?.textContent?.replace(/[^0-9.-]/g, '') || '0') || 0;

        const invitroColIdx = is7Category ? 12 : (is6Category ? 10 : -1);
        const numInVitroTests = invitroColIdx !== -1 ? parseFloat(tds[invitroColIdx]?.textContent?.replace(/[^0-9.-]/g, '') || '0') || 0 : 0;
        const inVitroTotal = invitroColIdx !== -1 ? parseFloat(tds[invitroColIdx + 1]?.textContent?.replace(/[^0-9.-]/g, '') || '0') || 0 : 0;

        const othersColIdx = is7Category ? 14 : (is6Category ? 12 : 10);
        const othersCost = parseFloat(tds[othersColIdx]?.textContent?.replace(/[^0-9.-]/g, '') || '0') || 0;
        const phaseNotes = tds[othersColIdx + 1]?.textContent?.trim() || '';

        // Back-calculate component parameter unit costs logically where possible
        const rowObj: PhaseRow = {
          id: `html-imported-row-${Date.now()}-${idx}`,
          tier: tierNum,
          phase: phaseName,
          description,

          isotopeCostPerBatch: 0,
          radiopharmConsumablesPerBatch: 0,
          radiopharmReagentsPerBatch: numBatches > 0 ? radioTotal / numBatches : radioTotal,
          numBatches,
          radiopharmFacilityCostPerHour: 0,
          radiopharmTaskTimeHoursPerBatch: 0,

          numAnimals,
          animalCostEach: numAnimals > 0 ? animalTotal / numAnimals : animalTotal,
          housingCostEach: 0,

          imagingConsumablesPerScan: 0,
          imagingReagentsPerScan: 0,
          numScans,
          scanCostPerHour: numScans > 0 ? imagingTotal / numScans : imagingTotal,
          scanTimeHoursPerScan: numScans > 0 ? 1 : 0,
          imageAnalysisHoursPerScan: 0,
          imageAnalysisCostPerHour: 0,

          clinicalImagingConsumablesPerScan: 0,
          clinicalImagingReagentsPerScan: 0,
          numClinicalScans,
          clinicalScanCostPerHour: numClinicalScans > 0 ? clinicalImagingTotal / numClinicalScans : clinicalImagingTotal,
          clinicalScanTimeHoursPerScan: numClinicalScans > 0 ? 1 : 0,
          clinicalImageAnalysisHoursPerScan: 0,
          clinicalImageAnalysisCostPerHour: 0,

          bioConsumablesPerBio: 0,
          bioReagentsPerBio: 0,
          numBiodistributions,
          bioCostPerUnit: numBiodistributions > 0 ? biodistributionTotal / numBiodistributions : biodistributionTotal,

          cellLineCost: 0,
          inVitroConsumablesPerTest: 0,
          inVitroReagentsPerTest: numInVitroTests > 0 ? inVitroTotal / numInVitroTests : inVitroTotal,
          numInVitroTests,
          inVitroTestingHoursPerTest: 0,
          inVitroTestingCostPerHour: 0,

          othersCost,
          othersNotes: '',
          phaseNotes,
          notes: phaseNotes
        };

        parsedRows.push(rowObj);
      });
    }

    if (parsedRows.length === 0) return null;

    // Itemized Line Item Breakdown table parsing fallback
    tableRows.forEach(tr => {
      const tds = tr.querySelectorAll('td');
      if (tds.length === 6) {
        const tierText = tds[0].textContent || '';
        const tierMatch = tierText.match(/\d+/);
        const tierNum = tierMatch ? parseInt(tierMatch[0], 10) : 1;
        const phaseName = (tds[1].textContent || '').trim();
        const fieldLabel = (tds[3].textContent || '').trim();
        const itemCell = tds[4];

        if (phaseName && fieldLabel && itemCell) {
          const targetRow = parsedRows.find(r => r.tier === tierNum && r.phase.toLowerCase() === phaseName.toLowerCase());
          if (targetRow) {
            if (!targetRow.itemizations) {
              targetRow.itemizations = {};
            }

            const keyMap: Record<string, keyof PhaseRow> = {
              'Isotope Cost ($/b)': 'isotopeCostPerBatch',
              'Radiopharm Consumables ($/b)': 'radiopharmConsumablesPerBatch',
              'Radiopharm Reagents ($/b)': 'radiopharmReagentsPerBatch',
              'Production Batches (n_b)': 'numBatches',
              'Facility Rate ($/h)': 'radiopharmFacilityCostPerHour',
              'Task Duration (h/b)': 'radiopharmTaskTimeHoursPerBatch',

              'Animal Quantity (n_a)': 'numAnimals',
              'Animal Purchase Cost ($/a)': 'animalCostEach',
              'Housing Cost ($/a)': 'housingCostEach',

              'Imaging Consumables ($/s)': 'imagingConsumablesPerScan',
              'Imaging Reagents ($/s)': 'imagingReagentsPerScan',
              'Scan Quantity (n_s)': 'numScans',
              'Scan Rate ($/h)': 'scanCostPerHour',
              'Scan Duration (h/s)': 'scanTimeHoursPerScan',
              'Image Analysis Duration (h/s)': 'imageAnalysisHoursPerScan',
              'Image Analysis Rate ($/h)': 'imageAnalysisCostPerHour',

              'Biodistribution Consumables ($/bio)': 'bioConsumablesPerBio',
              'Biodistribution Reagents ($/bio)': 'bioReagentsPerBio',
              'Biodistribution Quantity (n_bio)': 'numBiodistributions',
              'Biodistribution Unit Cost ($/unit)': 'bioCostPerUnit',

              'Cell Line Cost ($)': 'cellLineCost',
              'In Vitro Consumables ($/t)': 'inVitroConsumablesPerTest',
              'In Vitro Reagents ($/t)': 'inVitroReagentsPerTest',
              'In Vitro Test Quantity (n_t)': 'numInVitroTests',
              'In Vitro Testing Duration (h/t)': 'inVitroTestingHoursPerTest',
              'In Vitro Testing Rate ($/h)': 'inVitroTestingCostPerHour',

              'Other Direct Costs ($)': 'othersCost',

              // legacy and shorthand labels support
              'Isotope, $/b': 'isotopeCostPerBatch',
              'Consumables, $/b': 'radiopharmConsumablesPerBatch',
              'Reagents, $/b': 'radiopharmReagentsPerBatch',
              'Facility, $/h': 'radiopharmFacilityCostPerHour',
              'Task time, h/b': 'radiopharmTaskTimeHoursPerBatch',
              'Animals, $/a': 'animalCostEach',
              'Housing, $/a': 'housingCostEach',
              'Consumables, $/s': 'imagingConsumablesPerScan',
              'Reagents, $/s': 'imagingReagentsPerScan',
              'Scan cost, $/h': 'scanCostPerHour',
              'Scan time, h/s': 'scanTimeHoursPerScan',
              'Image analysis, h/s': 'imageAnalysisHoursPerScan',
              'Image analysis, $/h': 'imageAnalysisCostPerHour',
              'Consumables, $/bio': 'bioConsumablesPerBio',
              'Reagents, $/bio': 'bioReagentsPerBio',
              'Biodistribution cost, $/n_bio': 'bioCostPerUnit',
              'Cell line, $': 'cellLineCost',
              'Consumables, $/t': 'inVitroConsumablesPerTest',
              'Reagents, $/t': 'inVitroReagentsPerTest',
              'Tests, n_t': 'numInVitroTests',
              'Testing, h/t': 'inVitroTestingHoursPerTest',
              'Testing cost, $/h': 'inVitroTestingCostPerHour',
              'Others Cost, $': 'othersCost'
            };

            const fieldKey = keyMap[fieldLabel] || fieldLabel;
            if (!targetRow.itemizations[fieldKey as string]) {
              targetRow.itemizations[fieldKey as string] = [];
            }

            // Extract item nodes from div, li or text
            const itemElements = itemCell.querySelectorAll('.itemization-list > div, .itemization-list > li, li');
            if (itemElements.length > 0) {
              itemElements.forEach(el => {
                const text = el.textContent || '';
                const cleanText = text.replace(/^•\s*/, '').trim();
                const parts = cleanText.split(':');
                if (parts.length >= 2) {
                  const name = parts[0].trim();
                  const rawVal = parts.slice(1).join(':').replace(/[^0-9.-]/g, '');
                  const val = parseFloat(rawVal) || 0;
                  if (name) {
                    targetRow.itemizations![fieldKey as string].push({
                      id: `html-item-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
                      name,
                      value: val
                    });
                  }
                }
              });
            }
          }
        }
      }
    });

    const tierList: TierConfig[] = Array.from(foundTiers).sort((a, b) => a - b).map(num => {
      const existingDefault = DEFAULT_TIERS.find(t => t.tierNumber === num);
      return existingDefault || {
        tierNumber: num,
        name: `Tier ${num} Package`,
        subtitle: `Imported Campaign Scope Tier ${num}`
      };
    });

    return {
      tracerName: tracerName || 'Imported Campaign',
      selectedPresetId: 'custom',
      tiers: tierList.length > 0 ? tierList : DEFAULT_TIERS,
      rows: parsedRows,
      source: 'html_parsed'
    };
  } catch (err) {
    console.warn('Error during HTML fallback parsing:', err);
    return null;
  }
}

/**
 * Utility to parse single CSV line with quote escaping
 */
function parseCsvLine(line: string): string[] {
  const result: string[] = [];
  let current = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const char = line[i];
    if (char === '"') {
      if (inQuotes && line[i + 1] === '"') {
        current += '"';
        i++;
      } else {
        inQuotes = !inQuotes;
      }
    } else if (char === ',' && !inQuotes) {
      result.push(current.trim());
      current = '';
    } else {
      current += char;
    }
  }
  result.push(current.trim());
  return result;
}
